# Generated by Django 4.2.1 on 2023-07-18 13:44

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
